### ISSUE TITLE
Player circles are too big

### ISSUE THREAD

**Issue by langhillie** [Linus4/csgoverview#14]
Players are much bigger in the viewer than their area is in game, meaning they overlap with each other and the map a lot, stick out from corners when they are concealed in game, etc.

It's not a _major_ issue, so if smaller circles look much worse it's not too big of a deal

**Comment by Linus4** [comment]
It will probably have to stay like this for now. I chose this size because it more or less looks ok and there's enough space to display additional information.

There a bit more to it. For example, the overview image have different scales. So a player circle on Nuke should be smaller than one on Inferno. But then it all looks a bit cramped, especially if we make the circles smaller to begin with.
