### ISSUE TITLE
Copying player position/rotation

### ISSUE THREAD

**Issue by langhillie** [Linus4/csgoverview#16]
One of the main weaknesses of a 2d demo viewer is not being able to get grenade lineups. Adding an option to copy a players position and rotation to the clipboard would be extremely useful. Such a feature would copy to clipboard something like "setpos 1422.97 -248.02 -103.91;setang -43.12 -171.31" for a mirage top mid smoke, which you could then just paste into your console without having to load up CSGO's awful demo viewer

**Comment by Linus4** [comment]
That's a really cool idea. It might be difficult to implement, though, as I use only SDL2 for the user interface instead of a more powerful library. You cannot mark and copy text from SDL message boxes. So you would have to use a library like [atotto/clipboard](https://github.com/atotto/clipboard) - or something like this - for the output. These are murky waters, though, as it requires 'xclip' or 'xsel' to be installed on Linux. With Wayland on the horizon for many distributions, I think we might run into problems at some point?! Probably won't be too bad... 😄 

A keybind to access this feature would have to be added. Then you can show an SDL message box with a button for every player. Click on a player and the position will be copied to your clipboard...

One more thing: currently only `ViewDirectionX` is stored in the [Player](https://github.com/Linus4/csgoverview/blob/844cdb04aacfd0f0cf45c495fe67d29aa4faae5f/common/common.go#L88) type. `ViewDirectionY` would have to be added.

**Comment by langhillie** [comment]
If directly copying to clipboard cross platform would be tricky, would simply displaying the x/y view angles somewhere work? I know for my use case that would be slightly less convenient but still WAY ahead of loading up the demo in CSGO.

**Comment by langhillie** [comment]
I've been messing around a bit with this and it seems setpos often places players in a wall even for valid positions. That information is easy enough to get from the 2d viewer anyways, so it's not too big of a deal if we just return the angle.

**Comment by Linus4** [comment]
Does setpos place players close to their actual position or is it more random?
I think your PR looks good. Maybe we can get to the bottom of this setpos problem..

**Comment by Linus4** [comment]
At the moment, using the clipboard is preferrable to displaying the angle under the players, I think.

**Comment by langhillie** [comment]
Setpos places the player a few units above where they ask to be placed. So for some positions, it will put you in a ceiling. For example, here's a catwalk corner smoke that will put you half way into the wall. 
`setpos 1456 -104.03 -83.91;setang -21.54 177.97`
I just tested a little bit and it seems to place you approx 65 units above where you ask to be placed. If we subtract 64 from whatever position the game tells us the player is in, setpos seems to plop them in the correct spot without putting them into a wall. Subtracting 64 from the above broken command seems to work: 
`setpos 1456 -104.03 -147.91;setang -21.54 177.97`

As for the PR, I still need to get the Z position for the player and an SDL messagebox if you'd prefer that to the hotkey solution. If hotkeys are sufficient, I'll need to look at ordering the player list as currently the order seems random.

**Comment by Linus4** [comment]
I prefer the hotkeys now :D 

Regarding the player order: https://github.com/Linus4/csgoverview/blob/844cdb04aacfd0f0cf45c495fe67d29aa4faae5f/draw.go#L255
You can see that every player has an ID value (from the parser) and I sort the player slices before drawing the infobars. It's a bit of a hack, but it solves a few problems I had with the IDs.  There's definitely a better way to do this.

I think it's okay to handle every input (key) seperately, in this case.

**Comment by langhillie** [comment]
Ok, the PR is ready for review.

Would it be possible for us to sort the player list once when the demo is first being loaded? From my understanding we're sorting the list once a frame for the infobar. Maybe this should be made into a separate issue.

**Comment by langhillie** [comment]
Oh, and one last thing - Now that we effectively have 0-9 hotkeys assigned for each player, I think it would make sense to change the IDs shown for each player on the map/infobar to their respective hotkey. Also probably a new issue though

**Comment by Linus4** [comment]
I don't think we can sort the player list once at the start because every frame the match package looks up all the players that are connected to the server. Players might disconnect, stand-ins might continue the match. Unless, of course, we track the players over the course of the demo.

I agree with the ID => hotkey change ^^

**Comment by Linus4** [comment]
I've been using your new feature for the last few weeks and it's really cool and useful! :) Thank you for your contribution, I really appreciate it 💯 
I'll fix the player numbers on the infobars and maybe work on some issues for `v1.1.0` in the next few days.
