### ISSUE TITLE
Show currently held weapon

### ISSUE THREAD

**Issue by langhillie** [Linus4/csgoverview#26]
It would be useful to have some way of seeing what weapon players have in their hands. It could be through an icon, text above their name, or some other way

**Comment by Linus4** [comment]
Sounds like a really good idea. My preferred option would be to highlight the active weapon in the infobar. E.g. inactive weapons darker color, active weapon current color. Or add an outline? If a player has a nade or their knife out, is it important to highlight that as well? Or maybe it is enough to know if a player has their primary or secondary weapon equipped..?
In the future if we add icons for weapons and nades we could do it just like in the game. 
I'd rather display this information only on the infobars and not on the map.

**Comment by langhillie** [comment]
> If a player has a nade or their knife out, is it important to highlight that as well? 

I think so yeah. Sometimes players will hold a flash for someone, or jiggle/jumpspot with a smoke or molotov out. Sometimes it's nice to have that info.

**Comment by langhillie** [comment]
Another potential idea for how to solve this: 

When a player has a piece of utility held, attach the coloured square used for that utility to the player. It's not really important to see primary/secondary/knife, so I think this would be a decent solution with essentially no clutter.

**Comment by Linus4** [comment]
This sounds good. I assume it won't be confusing with other grenades on the screen that have actually been thrown. We could also draw the bomb icon if a player is holding the C4, so you can see if a player tries to plant the bomb before the site is cleared out properly ;)

Another idea: draw the little triangle on the player circle that indicates the player's view direction in red (same color as AWP shots) if the player has an AWP. Apart from AWPs, I don't really think it's important to see at a glance which gun a player is holding. Mayyybe something to indicate if a player is running around carelessly with his knife out :P I mean, it's either gonna be a gun-round and the players will have some kind of rifle, or it's an eco/armor+pistol round - and you'll notice that because it says so on the infobars ^^.

**Comment by Linus4** [comment]
216f853b4de9cb8ac45849494f579cea1ffbcf17 : players with AWP now have a red line-of-sight indicator

**Comment by Linus4** [comment]
resolved in f510deaf958983dee421ce66516066d19b95501c
