### ISSUE TITLE
Start Error

### ISSUE THREAD

**Issue by MiLaRi46** [Linus4/csgoverview#32]
Hello, with every demo I want to start, I get this error message. I have reinstalled the program several times, but without success.
![Unbenannt](https://user-images.githubusercontent.com/79254542/108341275-cc0a4880-71d9-11eb-9f42-714a8af29a82.PNG)

**Comment by Linus4** [comment]
Hi @MiLaRi46 , seems like this error comes straight from the parser library that we use to read the demo files.
Can you send me one of your demos so I can make some tests? You can drag & drop files directly on Github in the editor when you write a comment.
What kind of demos are you trying to watch? POV / GOTV demo? Your own Server / MM / faceit etc?

**Comment by MiLaRi46** [comment]
The file is unfortunately too large, which is why I uploaded it via wetransfer (https://we.tl/t-rZKVkEOdQq). This is a GOTV demo from a Faceit game.

**Comment by Linus4** [comment]
Okay, I'll look into it later today.

One quick question: I can play this demo on my computer. Faceit uses a program `gzip` (similar to winrar or 7zip) to compress the demos before you can download them. That's why the file is called `<demoname>.dem.gz`. Did you extract the actual `.dem` file from the `.gz` archive (using windows explorer, 7zip or any other archive program) before you tried opening it with csgoverview?

**Comment by MiLaRi46** [comment]
Okay thank you. Nice to know :D

**Comment by Linus4** [comment]
Sure, glad I could help :)
