### ISSUE TITLE
Can’t open demoviewer 

### ISSUE THREAD

**Issue by Zlatagurka** [Linus4/csgoverview#49]
**Describe the bug**
I’ve tried dozens of times to open the viewer but Whenber I try to run a demo through the application it says somethitn like. Can’t find HL20DEMo in the first 8bytes

**To Reproduce**
1. Go to wherever you have your hltv demos
2. Click on open with and choose demoreviewer
3. See error HL20DEMo not in the first 8 bytes

**Expected behavior*
Demoviewer has that error pop up and nothing happens

**Screenshots**

**Desktop 
Windows

**Additional context**

**Comment by Linus4** [comment]
Hi @Zlatagurka, thank you for bringing this to my attention! Maybe I need to update the version of the parser and build a new version. Could you provide links to the demos that you cannot open?

**Comment by Zlatagurka** [comment]
No file at all worked. I downloaded  10+ files but yes it did mention
something about parse. Really cool software

**Comment by Linus4** [comment]
I just downloaded a de_nuke demo and I could open the demo.
Couple of questions:
1. Did you **unpack the archive** if you've downloaded one from HLTV or Faceit? They compress their demos in a `.rar` or `.gz` archive to save bandwidth and space.
2. Did you try to watch a de_anubis demo?

**Comment by Zlatagurka** [comment]
Can you explain it step by step and I’ll do it right now

**Comment by Linus4** [comment]
Sure: If you 
1. download [this](https://www.hltv.org/matches/2360239/furia-fe-vs-b4-fe-esl-impact-league-season-2-finals) demo from HLTV, for example, you get a `.rar` file. 
2. You can open that file with a program like 7-Zip in order to extract the demo from the archive (drag and drop the `.dem` file out of the archive).
3. You can then open the `.dem` file with csgoverview.

**Comment by Zlatagurka** [comment]
It works :)
