### ISSUE TITLE
Bad rendering on mac

### ISSUE THREAD

**Issue by eriknikulski** [Linus4/csgoverview#7]
Hi, I got it working on mac but the drawings and text seems to be of very low resolution. Do you have any idea what the problem could be?

Screenshot:

<img width="1440" alt="Screenshot 2020-08-17 at 17 10 36" src="https://user-images.githubusercontent.com/32927151/90419375-c3b04400-e0b6-11ea-8283-78ee8bf3b3a3.png">

**Comment by Linus4** [comment]
Hi @eriknikulski , what resolution are you on? If it's anything lower than 1920x1080 then it's due to how the SDL's resolution indepent rendering works. 

I draw to a canvas with the size 1624x1024 pixels by default and then SDL scales it to the window size. A lot of lines (like those of player names and the circles) are very thin so they look weird after SDL has scaled them down.

Rewriting the `draw.go` file to do all of this scaling by hand is probably the biggest task that will have to be tackled at some point.

**Comment by eriknikulski** [comment]
Thanks! I have a logical resolution of 1440x900. So I adjusted the sizes
```go
winWidth             int32  = 1440
winHeight            int32  = 900
nameMapFontSize      int    = 14
mapOverviewWidth     int32  = 900
mapOverviewHeight    int32  = 900
mapXOffset           int32  = 270
mapYOffset           int32  = 0
infobarElementHeight int32  = 88
```

and changed the map scale in match.go

```go
match.MapScale = float32(meta.MapNameToMap[match.MapName].Scale) * 1024/900
```

and now it works pretty good.
